[package]
name = "sdmmc-phytium"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
tock-registers = "0"

[dev-dependencies]
bare-test = "0.0.5"

[build-dependencies]
sparreal-macros = "0.0.5"
